
GET http://localhost:3008/Gaader/gaader


###
GET  https://gaaders.herokuapp.com/Gaader/gaader

###
POST   http://localhost:3008/gaader/admin
content-type: application/json

{ 
    "gaade": ":))", "svar": "uuguy"  
    }


###
PATCH   https://gaaders.herokuapp.com/gaader/
content-type: application/json

{ 
    "gaade": ":DWA))", "svar": "uuguy"  
    }



###

DELETE http://localhost:3008/gaader/admin/5ee353185aa1c5426ca14548


###

DELETE https://gaaders.herokuapp.com/gaader/admin/5ee353185aa1c5426ca14548
